src/Entity/SecuredPaper.php
<?php

namespace App\Entity;

use App\Repository\SecuredPaperRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SecuredPaperRepository::class)]
class SecuredPaper
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $secured_paper_type = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSecuredPaperType(): ?string
    {
        return $this->secured_paper_type;
    }

    public function setSecuredPaperType(?string $secured_paper_type): static
    {
        $this->secured_paper_type = $secured_paper_type;

        return $this;
    }
}

src/Form/SecuredPaperType.php
<?php

namespace App\Form;

use App\Entity\SecuredPaper;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SecuredPaperType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('secured_paper_type')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => SecuredPaper::class,
        ]);
    }
}

src/Controller/SecuredPaperController.php
<?php

namespace App\Controller;

use App\Entity\SecuredPaper;
use App\Form\SecuredPaperType;
use App\Repository\SecuredPaperRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/secured/paper')]
final class SecuredPaperController extends AbstractController
{
    #[Route(name: 'app_secured_paper_index', methods: ['GET'])]
    public function index(SecuredPaperRepository $securedPaperRepository): Response
    {
        return $this->render('secured_paper/index.html.twig', [
            'secured_papers' => $securedPaperRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_secured_paper_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $securedPaper = new SecuredPaper();
        $form = $this->createForm(SecuredPaperType::class, $securedPaper);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($securedPaper);
            $entityManager->flush();
            //$entityManager->

            return $this->redirectToRoute('app_secured_paper_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('secured_paper/new.html.twig', [
            'secured_paper' => $securedPaper,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_secured_paper_show', methods: ['GET'])]
    public function show(SecuredPaper $securedPaper): Response
    {
        return $this->render('secured_paper/show.html.twig', [
            'secured_paper' => $securedPaper,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_secured_paper_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, SecuredPaper $securedPaper, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(SecuredPaperType::class, $securedPaper);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_secured_paper_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('secured_paper/edit.html.twig', [
            'secured_paper' => $securedPaper,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_secured_paper_delete', methods: ['POST'])]
    public function delete(Request $request, SecuredPaper $securedPaper, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$securedPaper->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($securedPaper);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_secured_paper_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/secured_paper/_delete_form.html.twig
<form method="post" action="{{ path('app_secured_paper_delete', {'id': secured_paper.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ secured_paper.id) }}">
    <button class="btn">Delete</button>
</form>

templates/secured_paper/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/secured_paper/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit SecuredPaper{% endblock %}

{% block body %}
    <h1>Edit SecuredPaper</h1>

    {{ include('secured_paper/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_secured_paper_index') }}">back to list</a>

    {{ include('secured_paper/_delete_form.html.twig') }}
{% endblock %}

templates/secured_paper/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}SecuredPaper index{% endblock %}

{% block body %}
    <h1>SecuredPaper index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Secured_paper_type</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for secured_paper in secured_papers %}
            <tr>
                <td>{{ secured_paper.id }}</td>
                <td>{{ secured_paper.name }}</td>
                <td>{{ secured_paper.securedPaperType }}</td>
                <td>
                    <a href="{{ path('app_secured_paper_show', {'id': secured_paper.id}) }}">show</a>
                    <a href="{{ path('app_secured_paper_edit', {'id': secured_paper.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_secured_paper_new') }}">Create new</a>
{% endblock %}

templates/secured_paper/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New SecuredPaper{% endblock %}

{% block body %}
    <h1>Create new SecuredPaper</h1>

    {{ include('secured_paper/_form.html.twig') }}

    <a href="{{ path('app_secured_paper_index') }}">back to list</a>
{% endblock %}

templates/secured_paper/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}SecuredPaper{% endblock %}

{% block body %}
    <h1>SecuredPaper</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ secured_paper.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ secured_paper.name }}</td>
            </tr>
            <tr>
                <th>Secured_paper_type</th>
                <td>{{ secured_paper.securedPaperType }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_secured_paper_index') }}">back to list</a>

    <a href="{{ path('app_secured_paper_edit', {'id': secured_paper.id}) }}">edit</a>

    {{ include('secured_paper/_delete_form.html.twig') }}
{% endblock %}